name: Create Release on Tag

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v6.0.2)'
        required: false

jobs:
  build_and_release_windows_installer:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Inno Setup
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install innosetup --no-progress --yes
      - name: Build Windows installer
        shell: pwsh
        run: |
          .\windows\installer\build-installer.ps1
      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: windows/installer/DDR5-AI-Memory-Tuner-Setup.exe
      - name: Create GitHub Release and attach installer
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            windows/installer/DDR5-AI-Memory-Tuner-Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
